### ISSUE TITLE
[Enhancement] Adding the definitions of the Steps into a model object for saving in a database 

### ISSUE THREAD

**Issue by ssmusoke** [mtownsend5512/progress#1]
Hello, have you considered storing the steps in the database to make it possible manage the steps separately and also configure multiple paths say Registration, Completing a list of Tasks

**Comment by mtownsend5512** [comment]
Since database connections vary depending on the PHP framework being used, that would make this package too narrow. This package was designed to be used in any PHP framework (or none at all).

If you wanted to set your web app up this way, you could still do this by creating your table and storing the validation methods and arguments in the database and running them dynamically.
